config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :users
  resources :posts
  resources :sessions, only: [:new, :create]
  delete '/logout' => 'sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # make the below methods available in our view templates:  
    helper_method :current_user, :logged_in?

    #return the current user (the user that's making a request at any given moment).
    def current_user
        @current_user || = User.find(session[:user_id]) if session[:user_id]
    end

    #return a simple boolean (are they logged in? true or false).
    def logged_in?
        !!current_user
    end
    
    #redirect the client to a different page if they try to access specific routes without being logged in.
    def authorize
        redirect_to new_session_path unless logged_in?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #verify who is logged in and only let person logged in edit or delte their own posts
  before_action :verify_user, only: [:edit, :update, :destroy]

  def index
    #search query
    if params[:q]
      #display search results, .where is looking for where it finds similarities "ILIKE" in "tag" to search query"?" "I" is "case Insensitive".
      @posts = Post.where("tag ILIKE ?", "%#{params[:q]}%")
    elsif params[:sort_by] == 'tag'
      #sort by Alphabetical 
      @posts = Post.order('tag')
      #display "Alphabetical" h1
      @header = "Alphabetical"
    elsif params[:sort_by] == 'created_at'
      #sort by Most Recent
      @posts = Post.order('created_at DESC')
      # display "Most Recent" h1
      @header = "Most Recent"
    elsif params[:sort_by] == 'random'
      #sort by Random
      @posts = Post.all.shuffle
      # display "Random" h1
      @header = "Random"
    else
      #default sort order
      @posts = Post.all.reverse
    end
  end

  def show
    id = params[:id]
    @post =  Post.find(id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    #define input for post audio field
    @post.audio = params[:post][:audio]
    #define input for post tag field
    @post.tag = params[:post][:tag]
    # set user to who is currently logged in
    @post.user_id = current_user.id
    if @post.save
      #take you back to your own user page after creating post
      redirect_to user_path(current_user.id)
    else
      render "new" #same as redirect_to new_product_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    #define input for post tag field
    @post.audio = params[:post][:audio]
    #define input for post tag field
    @post.tag = params[:post][:tag]
    @post.save
    #take you back to your own user page after creating post
    redirect_to user_path(current_user.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    #clears cookies
    session[:post_id] = nil
    redirect_to '/'
  end

  def verify_user
    #checks that the current logged in user is the same user who created the post
     @post = Post.find(params[:id])
     unless @post.user_id == current_user
     end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #look for a user with the provided email.
    @user = User.find_by_email(params[:email])
    #If there's a user with that email AND the password they provided is correct...
    if @user && @user.authenticate(params[:password])
      #add that user's ID to the session (the client will be given an updated cookie).
      session[:user_id] = @user.id

      ###########################################
      flash[:success] = "Welcome, #{@user.name}!"
      ###########################################
    
      #redirect to the user's profile (show) page.
      redirect_to user_path(@user)
    else
      ###########################################
      flash[:danger] = 'Incorrect email or password. Please try again.'
      ###########################################
    
      #otherwise, redirect back to the login form page to try again.
      redirect_to new_session_path
    end
  end

  def destroy
    #clear the user's ID out of the cookie
    session[:user_id] = nil
    #redirect to the home page 
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #restrict access
  #verify who is logged in and only let person logged in edit or delte their own posts
  before_action :authorize, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
    id = params[:id]
    @user =  User.find(id)
    @posts = @user.posts.all
   
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        redirect_to new_session_path
      else
        redirect_to new_user_path
      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.save
     #take you back to home page
    redirect_to '/'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
     #clears cookies
    session[:user_id] = nil
    redirect_to '/'
  end

  private
  def user_params
     #need these params to match up in order to log in
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body class="text-white">
    <%= render 'partials/navbar' %>
    <div class="container">
  
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
    </div>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/partials/_footer.html.erb
<nav class="navbar navbar-expand-lg bg-black footer center">
    <a href="https://www.facebook.com/spotify">
        <img src="https://i.imgur.com/p0GAlA5.png">
    </a>

    <a href="https://www.twitter.com/spotify">
        <img src="https://i.imgur.com/1lp3qGm.png">
    </a>

    <a href="https://www.instagram.com/spotify">
        <img src="https://i.imgur.com/fvGZoAR.png">
    </a>
</nav>

 

 

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-black ">
  <a class="navbar-brand">
    <%= link_to image_tag("https://i.imgur.com/LT1CSQd.png"), root_path, class: 'nav-link' %> 
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><%= link_to 'My Posts', user_path(current_user.id), class: 'nav-link' %>
          </a>

        <div class="dropdown-divider"></div>

        <a class="dropdown-item"> <%= link_to 'Edit Account', edit_user_path(current_user.id), class: 'nav-link' %>
        </a>

        <a class="dropdown-item"> <%= link_to 'Delete Account', logout_path, method: 'delete', class: 'nav-link' %>
        </a>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to 'New Post', new_post_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log Out', logout_path, method: 'delete', class: 'nav-link' %>
      </li>

    <% else %>

      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign In', new_session_path, class: 'nav-link' %>
      </li>

  <% end %>
    </ul>
    
    <form class="form-inline my-2 my-lg-0" action="/">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search
      </button>
    </form>
  </div>
</nav>

 

 

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Sign Up</h1>
    <%= form_for @post do |f| %>  
    <div class="form-group">
      <%= f.label :audio, 'Audio Track' %>
      <%= f.text_field :audio, class: 'form-control' %>
      <%= f.text_field :audio, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :tag, 'Tag' %>
        <%= f.text_field :tag, class: 'form-control' %>
      </div>

    <%= f.submit 'Edit Post', class: 'btn-spotify text-white' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% if params[:q] %>
  <h1>
    <%= @posts.length %> Search Results for "<%=params[:q]%>" 
  </h1> 
<% else %>

<div class="btn-group dropright btn-feed">
<h1 class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <% if @header %>
      <%= @header %>
      <% else %>
        Feed
      <% end %>
  </h1>


  <div class="dropdown-menu text-dark" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="?sort_by=tag">Alphabetical</a>
    <a class="dropdown-item" href="?sort_by=created_at">Most Recent</a>
    <a class="dropdown-item" href="?sort_by=random">Random</a>
  </div>
</div>
<% end %>

  <% @posts.in_groups_of(3).each_with_index do |row, i|  %>

    <div class="row mb-3">
      <div class="col-md-4 col-sm-12 col-sm-12" >
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <h5><%= link_to(row[0].user.name, user_path(row[0].user.id))%></h5>
            <%= row[0].audio.html_safe %>
            <p><%= link_to "#{time_ago_in_words(row[0].created_at)} ago", post_path(row[0]) %></p>
          </div>
        </div>
      </div>

    <% if row[1] %>
      <div class="col-md-4 col-sm-12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <h5><%= link_to(row[1].user.name, user_path(row[1].user.id))%></h5>
            <%= row[1].audio.html_safe %>
            <p><%= link_to "#{time_ago_in_words(row[1].created_at)} ago", post_path(row[1]) %></p>
          </div>
        </div>
      </div>
    <% end %>

    <% if row[2] %>
      <div class="col-md-4 col-sm-12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <h5><%= link_to(row[2].user.name, user_path(row[2].user.id))%></h5>
            <%= row[2].audio.html_safe %>
            <p><%= link_to "#{time_ago_in_words(row[2].created_at)} ago", post_path(row[2]) %></p>
          </div>
        </div>
      </div>
    <% end %>

  </div>
<% end %>

app/views/posts/new.html.erb
<body background="https://i.imgur.com/MO4O1X2.jpg">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1>New Post</h1>
      <%= form_for @post do |f| %>  
      <div class="form-group">
        <%= f.label :audio, 'Embed Code' %>
        <%= f.text_field :audio, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :tag, 'Tag' %>
        <%= f.text_field :tag, class: 'form-control' %>
      </div>

      <%= f.submit 'Create Post', class: 'btn-spotify text-white' %>
    <% end %>
    </div>
  </div>
</body>

app/views/posts/show.html.erb
<h1><%= link_to(@post.user.name, user_path(@post.user.id))%></h1> 

<div class="post-show">
    <div class="card" style="width: 342px;">
        <div class="card-body">
            <p><%= @post.audio.html_safe %></p>
            <p><%=time_ago_in_words @post.created_at %> ago</p>
            <% if current_user == @post.user %>
            <p>
                <%= link_to "Edit", edit_post_path(@post), class: "float-left" %> 
                <%= link_to "Delete", post_path(@post), {class: "float-right", method: "delete"} %>
            </p>
            <% end %>
        </div>
    </div>
 </div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Edit User Info</h1>
    <%= form_for @user do |f| %>  
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <%= f.submit 'Edit Account', class: 'btn-spotify text-white' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Feed</h1>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort By
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Alphabetical</a>
    <a class="dropdown-item" href="#">Most Recent</a>
    <a class="dropdown-item" href="#">Random</a>
  </div>
</div>

  <% @posts.shuffle.in_groups_of(3).each_with_index do |row, i|  %>

    <div class="row mb-3">
      <div class="col-md-4 col-sm\12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <h5><%= link_to(row[0].user.name, user_path(row[0].user.id))%></h5>
            <p> <%=time_ago_in_words row[0].created_at %> ago</p>
            <%= row[0].audio.html_safe %>
            <p><%= link_to(row[0].tag, post_path(row[0])) %></p>
          </div>
        </div>
      </div>

    <% if row[1] %>
      <div class="col-md-4 col-sm\12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <h5><%= link_to(row[1].user.name, user_path(row[1].user.id))%></h5>
            <p> <%=time_ago_in_words row[1].created_at %> ago</p>
            <%= row[1].audio.html_safe %>
            <p><%= link_to(row[1].tag, post_path(row[1])) %></p>
          </div>
        </div>
      </div>
    <% end %>

    <% if row[2] %>
      <div class="col-md-4 col-sm\12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <h5><%= link_to(row[2].user.name, user_path(row[2].user.id))%></h5>
            <p> <%=time_ago_in_words row[2].created_at %> ago</p>
            <%= row[2].audio.html_safe %>
            <p><%= link_to(row[2].tag, post_path(row[2])) %></p>
          </div>
        </div>
      </div>
    <% end %>

  </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">

    <h1>Sign Up</h1>
    
    <%= form_for @user do |f| %>  
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
      
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirm Password', class: 'control-label' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit 'Create Account', class: 'btn-spotify text-white' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% @posts.reverse.in_groups_of(3).each_with_index do |row, i|  %>
  <div class="row mb-3">
    <div class="col-md-4 col-sm\12">
      <div class="card" style="width: 342px;">
        <div class="card-body">
          <%= link_to(row[0].audio.html_safe, posts_path(row[0])) %>
          <p><%= link_to "#{time_ago_in_words(row[0].created_at)} ago", post_path(row[0]) %></p>
        <% if current_user == @user%>
          <p>
            <%= link_to "Edit", edit_post_path(row[0].id), class: "float-left" %> 
            <%= link_to "Delete", post_path(row[0].id), {class: "float-right", method: "delete"} %>
          </p>
        <% end %>
      </div>
    </div>
    </div>

    <% if row[1] %>
      <div class="col-md-4 col-sm\12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <%= link_to(row[1].audio.html_safe, posts_path(row[1])) %>
            <p><%= link_to "#{time_ago_in_words(row[1].created_at)} ago", post_path(row[1]) %></p>
            <% if current_user == @user %>
            <p>
              <%= link_to "Edit", edit_post_path(row[1].id), class: "float-left" %> 
              <%= link_to "Delete", post_path(row[1].id), {class: "float-right", method: "delete"}%>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  
    <% if row[2] %>
      <div class="col-md-4 col-sm\12">
        <div class="card" style="width: 342px;">
          <div class="card-body">
            <%= link_to(row[2].audio.html_safe, posts_path(row[2])) %>
            <p><%= link_to "#{time_ago_in_words(row[2].created_at)} ago", post_path(row[2]) %></p>
            <% if current_user == @user%>
            <p>
              <a><%= link_to "Edit", edit_post_path(row[2].id),class: "float-left" %> </a>
              <a class="right"><%= link_to "Delete", post_path(row[2].id), {class: "float-right", method: "delete"}%>
              </a>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>